title: "Ali Aghadadashi - Personal Blog"
author: "Ali Aghadadashi"
description: "M.Sc Graduated from Sharif University of Technology / AI & Process Engineer at Fanavaran_Sharif Company" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "aliagadadashi@gmail.com"
twitter_username: "ali_aghadadashi"
github_username: "aliagh11"
linkedin_username: "Ali Aghadadashi"
instagram_username: ali.aghadadashi
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: "hacker"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
